### ISSUE TITLE
Coordinate Reference system Conversion (to_crs) Not working

### ISSUE THREAD

**Issue by Mark-S-Bartlett** [Dewberry/pfra-hydromet#39]
For PrecipTable.ipynb, intersect_temporal_areas function, line: vol_gdf = vol_gdf.to_crs(geo_df.crs):

The conversion to a new crs (via to_crs) doesn't work for the first polygon in the dataframe being converted.

![Picture2](https://user-images.githubusercontent.com/42015329/80988001-df8e2380-8e00-11ea-9c92-12a7c21d0c53.jpg)

If the original database was a shapefile, the problem is fixed by setting os.environ["SHAPE_RESTORE_SHX"]= 'YES'.  Not sure how to fix this issue.

Thanks!

**Comment by Mark-S-Bartlett** [comment]
Fixed. Will request a pull/merge

**Comment by ShaneMPutnam** [comment]
I have not encountered this problem before but it seems to be an immutability issue if you can create a new object and it solves the problem. You could try: 
vol_gdf = gpd.read_file(datarepository_dir/Temporal_area_filename).to_crs(geo_df.crs).
